### ISSUE TITLE
Choose a Telegram lib for the bot

### ISSUE THREAD

**Issue by cristaloleg** [cristaloleg/monoid_bot#8]
Any proposals?

**Comment by TrollStation** [comment]
https://gopkg.in/telegram-bot-api.v4
I used this one before.

**Comment by cybervagabound2** [comment]
https://github.com/go-telegram-bot-api/telegram-bot-api

**Comment by cristaloleg** [comment]
@cybervagabound2 5.0.0 is RC, we prefer stable releases.
btw this is an alias for same lib :\

**Comment by cybervagabound2** [comment]
@cristaloleg ok, got it, just stared first lines in golang 20 minutes ago.

**Comment by cristaloleg** [comment]
https://github.com/tucnak/telebot/tree/v2 looks good for us
